information_information:
    resource: "@InformationBundle/Controller/InformationController.php"
    type:     annotation

information:
    resource: "@InformationBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }